### PR TITLE
Split code to accommodate neighbor functions

### PR DESCRIPTION
**Pull request by igorgatis**
This PR splits code into smaller parts to improve reuse. Once they get merged, they will allow writing a new function:
```py
def _s2_from_face_ij_wrap(face: int, i: int, j: int, level: int) -> int:
    i_same = (0 <= i < _S2_MAX_SIZE)
    j_same = (0 <= j < _S2_MAX_SIZE)
    if i_same and j_same:
        return _from_face_ij(face, i, j, level)
    elif (not i_same) and (not j_same):
        return 0

    scale = 1.0 / _S2_MAX_SIZE
    limit = math.nextafter(1, 2)
    u = max(-limit, min(limit, scale * ((2*i) + 1 - _S2_MAX_SIZE)))
    v = max(-limit, min(limit, scale * ((2*j) + 1 - _S2_MAX_SIZE)))

    face, u, v = _s2_xyz_to_face_uv(_s2_face_uv_to_xyz(face, (u, v)))
    return _s2_from_face_ij(
        face, _s2_st_to_ij(0.5 * (u + 1)), _s2_st_to_ij(0.5 * (v + 1)), level
    )
```

Then, we can use it to generate neighbors with:
```py
def get_neighbor_cell_ids(cellid: int, edge: bool = True, corners: bool = False) -> list[int]:
    level = cell_id_to_level(cellid)
    size = _get_size_ij(level)
    face, i, j = _to_face_ij_orientation(cellid)
    neighbors = []
    if edge:
        for di, dj in [(-size, 0), (0, size), (size, 0), (0, -size)]:
            neighbors.append(_s2_from_face_ij_wrap(face, i + di, j + dj, level))
    if corners:
        for di in (-size, size):
            for dj in (-size, size):
                neighbor = _s2_from_face_ij_wrap(face, i + di, j + dj, level)
                if neighbor > 0:
                    neighbors.append(neighbor)
    return neighbors
```

### CODE REVIEW

**Comment by aaliddell** [comment]
Could you do a force-push or null commit to kick off GH actions? I just had to re-enable the trigger due to inactivity and it hasn't picked up those tests :disappointed:

**Comment by igorgatis** [comment]
Shall we merge? BTW, should I send another PR with the neighbor related functions?

**Review by aaliddell — APPROVED** [review]

**Comment by aaliddell** [comment]
> Shall we merge? BTW, should I send another PR with the neighbor related functions?

Ok re second PR, but it'll need tests adding too to cover the new functions to ensure they match the reference impl

**Comment by igorgatis** [comment]
> > Shall we merge? BTW, should I send another PR with the neighbor related functions?
> 
> Ok re second PR, but it'll need tests adding too to cover the new functions to ensure they match the reference impl

Here it is #18

**Pull request merged**
